### ISSUE TITLE
Kip does not deploy before all services are build

### ISSUE THREAD

**Issue by TimVosch** [debugged-software/kip#6]
**Issue type:**

[ ] question
[x] on issue

**Kip version:**

[x] `latest`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Grab a repository with an independent helm chart deployment (so that it doesn't depend on a service.)
2. Have atleast one service with a Dockerfile that is not build yet.
3. Try to deploy the independent helm chart.
4. Observe Kip exiting:

```bash
$ kip deploy -c gateway                               
exit status 1
```

**Workaround**
Build all services:

```bash
$ kip build
...
```

**Comment by toonvanstrijp** [comment]
@TimVosch true! ;) we just fixed that issue in version v0.0.5
