### ISSUE TITLE
Bug when creating a new Helm chart inside of a kip service

### ISSUE THREAD

**Issue by Choem** [debugged-software/kip#7]
**Issue type:**

[] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Kip version:**

[X] `latest`
[ ] `0.x.x`

**Steps to reproduce or a small repository showing the problem:**

When you're inside a kip service and run `kip chart add new_service`, the Helm chart gets added in the root level deployment folder. I don't think this is the desired behavior, as we want the Helm chart to be placed in the deployments folder of the corresponding service.

**Comment by toonvanstrijp** [comment]
It depends on your project template `service/project`. When you have a kip `project` you need to specify the service where to add the chart by doing `-s [NAME]`. Otherwise it will end up in the root level deployment folder.
