### ISSUE TITLE
Kip deploy not working with docker desktop

### ISSUE THREAD

**Issue by martijndormans** [debugged-software/kip#8]
**Issue type:**

[ ] question
[ ] bug report
[X] feature request
[ ] documentation issue

**Kip version:**

[X] `latest`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Kip deploy uses minikube but that doesn't work with docker desktop:
![image](https://user-images.githubusercontent.com/21689486/78871332-d4d1b000-7a47-11ea-8265-076ff8901f65.png)

But when I use kip check minikube is not present:
![image](https://user-images.githubusercontent.com/21689486/78871281-c4213a00-7a47-11ea-86d6-e00ed168664e.png)

**Comment by toonvanstrijp** [comment]
@spoilerdo this issue isn't caused by kip, but by how you're using kip. Within your kip_config you probably run a script that causes this error.
